import './globals.css'
import {lato} from "./ui/fonts";
import {Providers} from "@/app/providers";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="es">
        <body className={`${lato.className} antialiased`}><Providers>{children}</Providers></body>
        </html>
    )
}
